import type { Metadata } from "next";
import localFont from "next/font/local";
import NewMessage from "@/components/NewMeassage";
import List from "../components/List/index";
import "./globals.css";
import GuestList from "@/components/GuestList";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <List id={0} message={""} />
        <GuestList listItem={null} />
        <NewMessage onSend={undefined}/>
        {children}
      </body>
    </html>
  );
}
